name: jstop
options:
  bundleIdPrefix: com.jstop
  minimumXcodeVersion: "14.0"
  deploymentTarget:
    macOS: "13.0"

settings:
  base:
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "13.0"
    ENABLE_HARDENED_RUNTIME: YES

targets:
  jstop:
    type: application
    platform: macOS
    sources:
      - jstop
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.jstop.jstop
        INFOPLIST_FILE: jstop/Info.plist
        CODE_SIGN_ENTITLEMENTS: jstop/jstop.entitlements
        CODE_SIGN_IDENTITY: "Developer ID Application"
        DEVELOPMENT_TEAM: "7AWFJS2W5C"
        CODE_SIGN_STYLE: Manual
    scheme:
      testTargets: []
